services:
  phpcs:
    image: ${IMAGES_PREFIX:-}phpcs
    build:
      context: ../../../
      dockerfile: deploy/local/docker/tools/Dockerfile
      target: phpcs
    volumes:
      - ../../../:/var/www/html

  phpmd:
    image: ${IMAGES_PREFIX:-}phpmd
    build:
      context: ../../../
      dockerfile: deploy/local/docker/tools/Dockerfile
      target: phpmd
    volumes:
      - ../../../:/var/www/html

  phpstan:
    image: ${IMAGES_PREFIX:-}phpstan
    build:
      context: ../../../
      dockerfile: deploy/local/docker/tools/Dockerfile
      target: phpstan
    volumes:
      - ../../../:/var/www/html

  php-cs-fixer:
    image: ${IMAGES_PREFIX:-}php-cs-fixer
    build:
      context: ../../../
      dockerfile: deploy/local/docker/tools/Dockerfile
      target: php-cs-fixer
      args:
        - PHP_VERSION=8.3 # requires PHP 8.3 for now (2025-04-10)
    volumes:
      - ../../../:/var/www/html
